services:
  - type: web
    name: lexigram-backend
    runtime: java
    buildCommand: ./gradlew clean build
    startCommand: java -jar build/libs/lexigram-*.jar --spring.profiles.active=render
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: render
      - key: DB_HOST
        value: dpg-d1ombiidbo4c73b84jug-a
      - key: DB_PORT
        value: 5432
      - key: DB_NAME
        value: lexigram_db
      - key: DB_USERNAME
        value: lexigram_db_user
      - key: DB_PASSWORD
        value: HNX0nArfBKzUIYsGhvEnGAFFZXSwG20F